from google.adk.agents import LlmAgent

from gen_code.code_gen_agent.common.config import AGENT_MODELS
from .prompt import agent_instruction

# Code Reviewer Agent
# Takes the code generated by the previous agent (read from state) and provides feedback.
code_reviewer_agent = LlmAgent(
    name="CodeReviewerAgent",
    model=AGENT_MODELS['code_reviewer'], # Specific model for reviewer, sourced from common.config
    instruction=agent_instruction,
    description="Reviews code and provides feedback.",
    output_key="review_comments",
)
